// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAgnYt6na9zRnCe7bW-TbkQRRte0-eWXU',
    appId: '1:212248974357:web:c887b05aa305bac3b3ea1c',
    messagingSenderId: '212248974357',
    projectId: 'flutterc2-b2796',
    authDomain: 'flutterc2-b2796.firebaseapp.com',
    storageBucket: 'flutterc2-b2796.firebasestorage.app',
    measurementId: 'G-ZVHW3P02PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPzNzVZmMVvBrnPbXY7WDQPL-dJVx5duM',
    appId: '1:212248974357:android:c0f2070cb164a8dbb3ea1c',
    messagingSenderId: '212248974357',
    projectId: 'flutterc2-b2796',
    storageBucket: 'flutterc2-b2796.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbQPgjWh_aopv0fYiUTnoKgtYEqIrxwBE',
    appId: '1:212248974357:ios:96e5b9537f5b2751b3ea1c',
    messagingSenderId: '212248974357',
    projectId: 'flutterc2-b2796',
    storageBucket: 'flutterc2-b2796.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbQPgjWh_aopv0fYiUTnoKgtYEqIrxwBE',
    appId: '1:212248974357:ios:96e5b9537f5b2751b3ea1c',
    messagingSenderId: '212248974357',
    projectId: 'flutterc2-b2796',
    storageBucket: 'flutterc2-b2796.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAgnYt6na9zRnCe7bW-TbkQRRte0-eWXU',
    appId: '1:212248974357:web:45f3a8fcdadf6f5ab3ea1c',
    messagingSenderId: '212248974357',
    projectId: 'flutterc2-b2796',
    authDomain: 'flutterc2-b2796.firebaseapp.com',
    storageBucket: 'flutterc2-b2796.firebasestorage.app',
    measurementId: 'G-YF8PE2PVVW',
  );
}
